### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'items')

### ISSUE THREAD

**Issue by JayDaMan53** [voidSevenSevenSix/BigIdeasMathMRLAnswersTool#1]
How Do I fix this?

**Comment by voidSevenSevenSix** [comment]
The console error should give you a line number, can you send it here?

**Comment by JayDaMan53** [comment]
I will when it is back up

**Comment by JayDaMan53** [comment]
here is my log after running
![image](https://user-images.githubusercontent.com/118361901/204826688-fdf2fb77-456b-4992-8957-6994f179ce60.png)

**Comment by voidSevenSevenSix** [comment]
There was a minor typo in the latest version, let me know if it works now (recopy the code, obviously).

**Comment by JayDaMan53** [comment]
![image](https://user-images.githubusercontent.com/118361901/205378086-9c27a666-ec92-4421-a002-b31ed786dde8.png)
new bug

**Comment by voidSevenSevenSix** [comment]
Duplicate at issue #2. Check there for updates. Closing this issue.
